name: nicholasjunge-website
description: Deploys nicholasjunge.com to AWS S3 + CloudFront
runtime:
  name: python
  options:
    toolchain: uv
    virtualenv: ../../.venv
config:
  # Override with: pulumi config set buildDir <path>
  buildDir:
    default: ../../build
